name: CD Deploy para VM Docker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ **Ignora COMPLETAMENTE o diretório padrão do SSH**
      - name: Configurar SSH em /tmp (à prova de falhas)
        run: |
          SSH_TEMP="/tmp/ssh_$GITHUB_RUN_ID"
          mkdir -p "$SSH_TEMP"
          echo "${{ secrets.HOMOLOG_VM_KEY }}" > "$SSH_TEMP/id_ed25519"
          chmod 700 "$SSH_TEMP"
          chmod 600 "$SSH_TEMP/id_ed25519"
          ssh-keyscan -H "${{ secrets.HOMOLOG_VM_HOST }}" > "$SSH_TEMP/known_hosts"
          echo "SSH_DIR=$SSH_TEMP" >> $GITHUB_ENV

      # 🔍 **Teste de conexão com debug explícito**
      - name: Testar SSH (com logs detalhados)
        run: |
          ssh -vvv -i "$SSH_DIR/id_ed25519" \
              -o UserKnownHostsFile="$SSH_DIR/known_hosts" \
              -o StrictHostKeyChecking=no \
              "${{ secrets.HOMOLOG_VM_USER }}@${{ secrets.HOMOLOG_VM_HOST }}" \
              "echo '✅ Conexão SSH bem-sucedida!'" || (echo "::error::Falha na conexão SSH"; exit 1)

      # 🚀 **Deploy sem depender de ~/.ssh**
      - name: Deploy na VM
        run: |
          rsync -avz --delete \
            -e "ssh -i $SSH_DIR/id_ed25519 -o UserKnownHostsFile=$SSH_DIR/known_hosts" \
            ./ \
            "${{ secrets.HOMOLOG_VM_USER }}@${{ secrets.HOMOLOG_VM_HOST }}:/docker/"
          
          ssh -i "$SSH_DIR/id_ed25519" \
              "${{ secrets.HOMOLOG_VM_USER }}@${{ secrets.HOMOLOG_VM_HOST }}" \
              "cd /docker && docker-compose up -d --build"
