name: CD Deploy para VM Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOMOLOG_VM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.56.81 >> ~/.ssh/known_hosts

      - name: Copiar arquivos para a VM (/docker)
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes" ./ ${{ secrets.HOMOLOG_VM_USER }}@${{ secrets.HOMOLOG_VM_HOST }}:/docker/

      - name: Build e executar Docker container na VM
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes ${{ secrets.HOMOLOG_VM_USER }}@${{ secrets.HOMOLOG_VM_HOST }} "
            cd /docker && \
            docker build -t python-app:latest . && \
            docker rm -f python-app || true && \
            docker run -d --name python-app --restart unless-stopped -p 8000:8000 python-app:latest
          "
