name: Python CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagem Docker
        run: docker build -t meuapp:ci .

      - name: Rodar app.py no container
        run: docker run --rm meuapp:ci
