name: Build Docker Images

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build -t backend:latest -f Dockerfile.backend .

      - name: Build frontend image
        run: |
          docker build -t frontend:latest -f Dockerfile.frontend .

      # Se quiser salvar como artefato para deploy, descomente abaixo:
      # - name: Save backend image as artifact
      #   run: docker save backend:latest -o backend.tar
      # - name: Save frontend image as artifact
      #   run: docker save frontend:latest -o frontend.tar

      # - name: Upload backend image
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: backend-image
      #     path: backend.tar
      # - name: Upload frontend image
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frontend-image
      #     path: frontend.tar