name: CI/CD Pipeline Python App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instala ferramentas de build
        run: pip install --upgrade pip setuptools wheel

      - name: Gera pacote .whl
        run: python setup.py bdist_wheel

      - name: Salva artefato .whl
        uses: actions/upload-artifact@v4
        with:
          name: pacote-wheel
          path: dist/*.whl

      - name: Build imagem Docker
        run: docker build -t meuapp:ci .

      - name: Rodar app.py no container
        run: docker run --rm meuapp:ci

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - usuário e home
        run: |
          whoami
          echo "Home: $HOME"
          ls -la ~
          ls -la ~/.ssh || echo "~/.ssh não existe"

      - name: Build Docker image
        run: |
          set -euxo pipefail
          cd 01-dev-desktop-local
          docker build -t python-app:latest .

      - name: Remove old container (if exists)
        run: |
          docker rm -f python-app || true

      - name: Run Docker container (background)
        run: |
          docker run -d --name python-app -p 8000:8000 python-app:latest