name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          # Vai para o diretório já existente
          cd /docker/devops-ci-cd
          
          # Atualiza com os novos arquivos (usando o checkout atual)
          cp -r $GITHUB_WORKSPACE/* .
          cp -r $GITHUB_WORKSPACE/.* . 2>/dev/null || true
          
          # Build e deploy
          docker build -t backend:latest .
          docker stop backend 2>/dev/null || true
          docker rm backend 2>/dev/null || true
          docker run -d --name backend -p 5000:5000 backend:latest
          
          echo "Deploy completed!"
