name: Deploy Python App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - usuário e home
        run: |
          whoami
          echo "Home: $HOME"
          ls -la ~
          ls -la ~/.ssh || echo "~/.ssh não existe"

      - name: Build and run Docker container
        run: |
          set -euxo pipefail
          cd 01-dev-desktop-local
          docker build -t python-app:latest .
          docker rm -f python-app || true
          docker run --name python-app --rm python-app:latest

