name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOMOLOG_VM_HOST }}
          username: ${{ secrets.HOMOLOG_VM_USER }}
          key: ${{ secrets.HOMOLOG_VM_KEY }}
          script: |
            cd /caminho/do/projeto # <-- ajuste para o caminho correto do seu projeto na VM
            git pull origin main
            docker stop backend || true
            docker rm backend || true
            # docker stop frontend || true
            # docker rm frontend || true
            docker build -t backend:latest -f Dockerfile .
            # docker build -t frontend:latest -f frontend/Dockerfile frontend
            docker run -d --name backend -p 5000:5000 backend:latest
            # docker run -d --name frontend -p 8080:8080 frontend:latest
