name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /caminho/do/projeto
            git pull origin main
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true
            docker build -t backend:latest -f backend/Dockerfile backend
            docker build -t frontend:latest -f frontend/Dockerfile frontend
            docker run -d --name backend -p 5000:5000 backend:latest
            docker run -d --name frontend -p 8080:8080 frontend:latest
