name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare deployment directory
        run: |
          DEPLOY_DIR="/docker/devops-ci-cd"
          sudo mkdir -p $DEPLOY_DIR
          sudo chown -R $USER:$USER $DEPLOY_DIR
          
          # Sincroniza arquivos mantendo permissões
          rsync -av --delete ./ $DEPLOY_DIR/

      - name: Build Docker image
        run: |
          cd /docker/devops-ci-cd
          docker build -t backend:latest -f Dockerfile .

      - name: Stop and remove old container
        run: |
          docker stop backend 2>/dev/null || true
          docker rm backend 2>/dev/null || true

      - name: Deploy new container
        run: |
          docker run -d \
            --name backend \
            -p 5000:5000 \
            -v /docker/devops-ci-cd:/app \
            backend:latest

      - name: Verify deployment
        run: |
          sleep 5
          echo "Verificando se o container está rodando..."
          docker ps | grep backend
          curl -f http://localhost:5000 || echo "Health check falhou, mas container pode estar iniciando"
