name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOMOLOG_VM_HOST }}
          username: ${{ secrets.HOMOLOG_VM_USER }}
          key: ${{ secrets.HOMOLOG_VM_KEY }}
          script: |
            # Garante que o diret처rio existe, se n찾o existir, cria
            if [ ! -d "/docker/devops-ci-cd" ]; then
              mkdir -p /docker/devops-ci-cd
            fi

            cd /docker/devops-ci-cd
            # Inicializa o reposit처rio git se ele n찾o existir (apenas na primeira vez)
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/JMJ22/devops-ci-cd.git
              git fetch origin
              git checkout -t origin/main
            else
              git pull origin main
            fi

            docker stop backend || true
            docker rm backend || true
            # docker stop frontend || true
            # docker rm frontend || true
            docker build -t backend:latest -f Dockerfile .
            # docker build -t frontend:latest -f frontend/Dockerfile frontend
            docker run -d --name backend -p 5000:5000 backend:latest
            # docker run -d --name frontend -p 8080:8080 frontend:latest
