name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Ensure deployment directory exists
        run: |
          sudo mkdir -p /docker/devops-ci-cd
          sudo chown -R $USER:$USER /docker/devops-ci-cd

      - name: Checkout code to deployment directory
        uses: actions/checkout@v3
        with:
          path: /docker/devops-ci-cd

      - name: Build and deploy
        run: |
          cd /docker/devops-ci-cd
          
          # Build da imagem
          docker build -t backend:latest .
          
          # Para e remove container antigo
          docker stop backend 2>/dev/null || true
          docker rm backend 2>/dev/null || true
          
          # Executa novo container
          docker run -d \
            --name backend \
            -p 5000:5000 \
            backend:latest

      - name: Health check
        run: |
          sleep 3
          docker ps
          echo "Deploy completed successfully!"
