name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy backend
        run: |
          cd /docker/devops-ci-cd
          cp -r $GITHUB_WORKSPACE/* .
          cp -r $GITHUB_WORKSPACE/.* . 2>/dev/null || true

          docker build -t backend:latest -f Dockerfile.backend .
          docker stop backend 2>/dev/null || true
          docker rm backend 2>/dev/null || true
          docker run -d --name backend -p 5000:5000 backend:latest

      - name: Build and deploy frontend
        run: |
          cd /docker/devops-ci-cd
          docker build -t frontend:latest -f Dockerfile.frontend .
          docker stop frontend 2>/dev/null || true
          docker rm frontend 2>/dev/null || true
          docker run -d --name frontend -p 8080:80 frontend:latest

      - name: Done
        run: echo "Deploy completed!"