name: Python CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r 01-dev-desktop-local/requirements.txt
      - name: Run flake8 linter
        run: |
          pip install flake8
          flake8 01-dev-desktop-local/
      - name: Run tests
        run: pytest 01-dev-desktop-local/test_app.py
